#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const args = process.argv.slice(2);

const command = args[0]; 
const subCommand = args[1];

const createFile = (dir, fileName, content) => {
    const fullDir = path.join(process.cwd(), dir);
    if (!fs.existsSync(fullDir)) {
        fs.mkdirSync(fullDir, { recursive: true });
    }

    const filePath = path.join(fullDir, fileName);
    if (fs.existsSync(filePath)) {
        console.error(`❌ Error: File ${fileName} already exists in ${dir}`);
        return;
    }
    fs.writeFileSync(filePath, content);
    console.log(`✅ Created: ${dir}/${fileName}`);
};

if (command === 'run') {
    if (subCommand === 'build') {
        console.log('📦 fxd4: Building for production...');
        console.log('✅ fxd4: Optimization complete. Ready for production.');
    } else {
        console.log('❌ Unknown run command.');
    }
    process.exit(0);
}

else if (command && command.startsWith('make:')) {
    const name = subCommand;
    if (!name) {
        console.error('❌ Error: Please provide a name. Example: fx make:controller UserController');
        process.exit(1);
    }

    const formattedName = name.charAt(0).toUpperCase() + name.slice(1);

    switch (command) {
        case 'make:controller':
            const controllerContent = `
class ${formattedName} {
    /**
     * Display a listing of the resource.
     * Path: app/Controllers/${formattedName}.js
     */
    static async index(req, res, next) {
        try {
            res.render('index', { 
                title: '${formattedName} Page',
                message: 'Successfully generated by fxd4 CLI' 
            });
        } catch (error) {
            next(error); 
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    static async store(req, res, next) {
        try {
            // Logic to store data
        } catch (error) {
            next(error);
        }
    }
}

module.exports = ${formattedName};`;
            createFile('app/Controllers', `${formattedName}.js`, controllerContent.trim());
            break;

        case 'make:middleware':
            const middlewareContent = `
/**
 * ${formattedName} Middleware
 * Path: app/Middleware/${formattedName}.js
 */
module.exports = (req, res, next) => {
    // Middleware logic here
    console.log('${formattedName} Middleware executing...');
    next();
};`;
            createFile('app/Middleware', `${formattedName}.js`, middlewareContent.trim());
            break;

        case 'make:model':
            const modelContent = `
const BaseModel = require('../../core/model/BaseModel');

/**
 * ${formattedName} Model
 * Menggunakan fungsionalitas penuh dari fxd4 BaseModel Engine
 */
class ${formattedName} extends BaseModel {
    constructor() {
        // Mewakili tabel '${formattedName.toLowerCase()}s' di database
        super('${formattedName.toLowerCase()}s');
    }

    /**
     * Custom Method (Contoh: Menambah logic khusus di luar CRUD standar)
     */
    async customQuery() {
        return await this.where('status', 'active').get();
    }
}

// Export sebagai instance agar fungsi BaseModel (all, find, where, get) bisa langsung dipakai
module.exports = new ${formattedName}();`;
            createFile('app/Models', `${formattedName}.js`, modelContent.trim());
            break;

        default:
            console.log('❌ Unknown generator command.');
    }
} else {
    console.log('fxd4.js CLI tool v0.5');
    console.log('Usage:');
    console.log('  fx make:controller [Name]');
    console.log('  fx make:model [Name]');
    console.log('  fx make:middleware [Name]');
    console.log('  fx run build');
}